server:
  port: 8083

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/shopmart_payment?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

payment:
  simulate-failure: false
  max-amount: 80000000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: payment-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
